### ISSUE TITLE
Strategy for deployment/containerisation

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/Soul4ReactAdmin#4]
One day I will deploy the Soul/ReactAdmin solution to the target network.

I'm familiar with deploying apps, and `yarn build`, etc.

But, I'd like to consider containerising the solution.

@AbegaM - can you suggest a neat & tidy strategy for deploying the solution as one or more docker containers?

**Comment by ebenezer-melkamu** [comment]
@IanMayo I think the best way would be to deploy the React admin UI and the Soul wrapper in separate docker containers, we can add a `Dockerfile` in the soul wrapper and we can pull the `SQLite3` docker image in there and we can deploy the containers in a cloud service like AWS Lightsail, but i will find out if there is a better alternative for the deployment.

**Comment by IanMayo** [comment]
AWS is a good suggestion, but my clients will be hosting it on their own network.

**Comment by IanMayo** [comment]
React admin UI: But the compiled React app is just a static website . Having its own docker _seems_ like overkill, IMHO.  But, you're the backed dev, not me :-)

**Comment by ebenezer-melkamu** [comment]
My experience is mostly with developing backend APIs, i have deployed some projects but i wasn't more focused in the DevOps part, but if you can point me to a better way for the deployment I can set up everything quickly.

**Comment by IanMayo** [comment]
done
